{% set name = "ximage" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ximage-{{ version }}.tar.gz
  sha256: aac64207f4216337eaf534aa1eb9e89dd38f7fc0db41e121f95b7b002e339f47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - xarray
    - dask-core
    - dask-image
    - matplotlib-base
    - scikit-image

test:
  imports:
    - ximage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ghiggi/ximage
  summary: xarray-based tools for image/video processing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ghiggi
